#ifndef ETCDATA_H_
#define ETCDATA_H_

#include "image.h"

enum {
  ACTION_NORMAL,
  ACTION_DANCE,
  ACTION_CRY,
  ACTION_SLEEP,
  ACTION_SIT,
  ACTION_LIE,
  ACTION_STROKE,
  ACTION_WOW,
  ACTION_DIE,
};
/*
  enum{
  BODY_SAMPLE,BODY_NORMAL0,BODY_NORMAL1,BODY_WOW,
  BODY_HEY,BODY_THAT,BODY_BACK,BODY_SIT,BODY_LIE,BODY_SLEEP0,BODY_SLEEP1,
  BODY_DIE,BODY_WHAT,BODY_TYOKON,BODY_MOJI0,BODY_MOJI1,BODY_IMAGENUM
  };
  enum{
  EYE_NORMAL,EYE_SLEEPY0,EYE_SLEEPY1,EYE_CLOSE,EYE_HAPPY,EYE_SURPRISE,
  EYE_ZITO,EYE_HOW,EYE_WINK,EYE_HIDE
  };*/

const uint8_t action_normal[6][2] PROGMEM = {
  {1, 2},
  {3, 4},
  {5, 6},
  {7, 8},
  {9, 10},
  {NULL, NULL},
};

const uint8_t action_normalt[3][2] PROGMEM = {
  {101, 102},
  {103, 104},
  {NULL, NULL},
};

const uint8_t* act[2] = { &action_normal[0][0], &action_normalt[0][0] };

const uint8_t anime_normal[17][2] PROGMEM = {
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  
  {BODY_NORMAL1,EYE_CLOSE},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_CLOSE},
  {BODY_NORMAL0,EYE_NORMAL},
  
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_CLOSE},
  {BODY_NORMAL1,EYE_NORMAL},
  
  {BODY_NORMAL0,EYE_CLOSE},
  {NULL, NULL},
};

const uint8_t anime_sleeping[7][2] PROGMEM = {
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  
  {BODY_SLEEP1,EYE_CLOSE},
  {NULL,NULL},
};

const uint8_t anime_sleepy[12][2] PROGMEM = {
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  
  {BODY_SIT,EYE_CLOSE},
  {NULL,NULL},
};



/*
const uint8_t* animations[] = {
  &anime_normal[0][0],
  &anime_sleeping[0][0],
};*/

#endif
